#!/bin/python3
import sys, getopt
from os import system
from termcolor import colored
from audoai.noise_removal import NoiseRemovalClient

def remNoise(inputfile, outputfile):
    print ('Input file is ', inputfile)
    noise_removal = NoiseRemovalClient(api_key="<API_KEY>")
    result = noise_removal.process(inputfile)
    print(result.url)
    result.save(outputfile)
    print ('Output file is stored in current directory ', outputfile)


def main(argv):
   inputfile = ''
   outputfile = ''
   #banner
   system('jp2a --colors https://i.ibb.co/t3673SC/audo-logo.png')
   print(colored('-/hakxcore  v1.0.0'.center(190),'green'))
   #system("echo '\033[0;37m'")
   print('_'*110)
   print('\n\n')
   opts, args = getopt.getopt(argv,"hi:o:",["ifile=","ofile="])
   for opt, arg in opts:
      if opt == '-h':
         print ('audo -i <inputfile> -o <outputfile>')
         sys.exit()
      elif opt in ("-i", "--ifile"):
         inputfile = arg
      elif opt in ("-o", "--ofile"):
         outputfile = arg
   remNoise(inputfile, outputfile)

if __name__ == "__main__":
   main(sys.argv[1:])
